version: "3"
services:
  source-code-marking:
    build:
      context: .
    restart: always
    depends_on: 
      - mongo
    entrypoint: ["/app/server"]
    expose:
      - ${PORT}
    environment:
      DB_HOST: "mongodb://mongo:27017"

  mongo:
    image: "mongo:4.2.1"
    container_name: "mongo"
    volumes:
      - "mongo:/data/db"
    ports:
      - "27100:27017"

  nginx:
    image: nginx:latest
    build:
      dockerfile: deployments/Dockerfile
      context: .
    volumes:
      - ./deployments/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - source-code-marking
    ports:
      - "4000:4000"
volumes:
  mongo:
