version: "3"
services:
  source-code-marking:
    build:
      context: .
    env_file: .env
    restart: always
    depends_on: 
      - mongo
    volumes:
      - .:/app/src
    expose:
      - ${PORT}
    environment:
      DB_HOST: "mongodb://mongo:27017"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

  mongo:
    image: "mongo:4.2.1"
    container_name: "mongo"
    volumes:
      - "mongo:/data/db"
    ports:
      - "27100:27017"

  nginx:
    image: nginx:alpine
    build:
      context: ./deployments
      dockerfile: Dockerfile
    volumes:
      - ./deployments/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - source-code-marking
    ports:
      - "4000:4000"
  redis:
    image: "redis:alpine"

volumes:
  mongo:
