version: "3"
services:
  back_end:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    depends_on: 
      - mongo
    volumes:
      - .:/app/src
    expose:
      - ${PORT}
    environment:
      DB_HOST: "mongodb://mongo:27017"
      REDIS_HOST: "redis:6379"
      REDIS_DB: 0
      REDIS_PASSWORD: password

  mongo:
    image: "mongo:4.2.1"
    container_name: "mongo"
    volumes:
      - "mongo:/data/db"
    ports:
      - "27100:27017"

  nginx:
    image: nginx:alpine
    build:
      context: ./deployments
      dockerfile: Dockerfile
    volumes:
      - ./deployments/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - source-code-marking
    ports:
      - "4000:4000"

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    volumes:
      - ./tmp/redis-data:/var/lib/redis
      - ./tmp/redis.conf:/usr/local/etc/redis/redis.conf
    ports: 
      - "6378:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  
  front_end:
    image: nginx:alpine
    command: git -C /build clone https://github.com/1653014/SourceCodeMarking_React.git
volumes:
  mongo:
